pipeline {
    agent any

    stages {
        stage('Pipeline Init') {
            steps {
                echo 'Pipeline Init..'
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('Run Migrations') {
            steps {
                echo 'Run Migrations....'
            }
        }
    }
}